package com.gb.restaurant.enumm

enum class Support {
    REQUEST_CALL_BACK,HELP_ADDING_TIPS,HELP_ADDING_ITEM,HELP_CANCEL_REFUND,UPDATE_MENU,ADDING_NEW_STORE,FREE_WEBSITE,REVIEW_ON_GOOGLE,MARKETING_PACKAGE,PAYMENT_BANK

}